"""
draft_app.py  --  Draft Wizard (Streamlit)
===========================================
Phone-friendly live draft assistant. Mark players off as they're drafted (tap a
row, tap a chip, search, or auto-sync from Sleeper) and it recomputes the best
pick, tiers, survival odds, and how your opponents are drafting after every pick.

Local:   streamlit run draft_wizard/draft_app.py
Phone:   deploy this folder to Streamlit Community Cloud (see README) -> open the
         https URL on your phone.

LAYOUT -- this is a draft-room screen, not a dashboard. Everything you act on
while a pick clock is running lives above the fold and needs no clicks:
    status bar -> recommendation -> best available + who's on deck
Everything you consult BETWEEN picks (full board, team shapes, forward plan,
practice controls) is in the tab strip below it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent))
from draft_engine import (load_board, LeagueConfig, analyze, plan_draft,   # noqa: E402
                          ARCHETYPES, ARCHETYPE_LABEL, prep_valued, mock_advance,
                          team_on_clock, grade_draft)
import draft_review as DR                                    # noqa: E402
import mock_history as MH                                    # noqa: E402
from draft_board import (draft_board_html, on_deck_html, run_strip_html,     # noqa: E402
                         roster_matrix_html, team_rosters_html, status_bar_html,
                         slot_team, pick_label, POS_BG)
from draft_names import norm_name, pos_norm, surname                          # noqa: E402

# quick-league presets (the main axes; roster stays standard, your slot is separate)
PRESETS = {
    "12-team PPR (1QB)":       dict(teams=12, scoring="ppr",      superflex=False),
    "12-team Half PPR (1QB)":  dict(teams=12, scoring="half",     superflex=False),
    "12-team PPR Superflex":   dict(teams=12, scoring="ppr",      superflex=True),
    "10-team PPR (1QB)":       dict(teams=10, scoring="ppr",      superflex=False),
    "14-team PPR (1QB)":       dict(teams=14, scoring="ppr",      superflex=False),
    "12-team Standard (1QB)":  dict(teams=12, scoring="standard", superflex=False),
}

# DraftKings Best Ball, verified against DK's published rules: 20 roster spots,
# weekly lineup QB/2RB/3WR/TE/FLEX, no K or DST, snake, 12 teams. Scoring is DK
# classic (full PPR + 3 at 300 pass / 100 rush / 100 rec yards) -- the board is
# PPR, and the bonuses are a small monotone add on top, so `ppr` is the right
# setting for the reception term here.
DK_BESTBALL = dict(
    teams=12, scoring="ppr", superflex=False, snake=True, rounds=20, bench=12,
    kind="bestball", best_ball=True,
    starters={"QB": 1, "RB": 2, "WR": 3, "TE": 1, "FLEX": 1,
              "SUPERFLEX": 0, "K": 0, "DST": 0},
)
PRESETS["DraftKings Best Ball — 12T 20rd"] = dict(DK_BESTBALL)


def _load_league_presets():
    """Merge the generic presets with YOUR real leagues from data/league_presets.json
    (generated by import_leagues.py from Sleeper/ESPN)."""
    merged = {k: dict(v) for k, v in PRESETS.items()}
    p = Path(__file__).parent / "data" / "league_presets.json"
    if p.exists():
        try:
            for x in json.load(open(p, encoding="utf-8")).get("presets", []):
                merged[x["name"]] = x
        except Exception:
            pass
    return merged


ALL_PRESETS = _load_league_presets()

st.set_page_config(page_title="Draft Wizard", page_icon="🏈", layout="wide",
                   initial_sidebar_state="expanded")

# Tighten Streamlit's default spacing -- a draft screen wants density, and the
# stock 6rem top padding pushes the recommendation below the fold on a phone.
st.markdown("""
<style>
  .block-container {padding-top: 1.2rem; padding-bottom: 2rem; max-width: 1500px;}
  div[data-testid="stMetricValue"] {font-size: 1.35rem;}
  div[data-testid="stVerticalBlockBorderWrapper"] {border-radius: 10px;}
  .stTabs [data-baseweb="tab"] {padding: 6px 14px;}
  .dw-rec {border:1px solid #334155;border-left:5px solid #f59e0b;border-radius:10px;
           background:#0f172a;padding:12px 14px;margin-bottom:6px;}
  .dw-rec h3 {margin:0 0 4px 0;font-size:1.25rem;color:#f1f5f9;}
  .dw-pill {display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px;
            font-weight:700;color:#fff;margin-right:5px;}
  .dw-sub {color:#94a3b8;font-size:12px;margin-top:6px;}
  .dw-h {color:#94a3b8;font-size:11px;text-transform:uppercase;letter-spacing:.07em;
         font-weight:700;margin:10px 0 4px 0;}
  /* Streamlit buttons break on any character, so a stretched button in a narrow
     column renders its label one letter per line -- the quick-pick chips were a
     vertical alphabet on a 958px laptop. Truncate instead. */
  .stButton button p {white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
                      word-break: keep-all;}
</style>""", unsafe_allow_html=True)


@st.cache_data(show_spinner=False)
def get_board():
    return load_board()


@st.cache_data(show_spinner=False)
def get_tendencies():
    """Manager habits from this league's OWN past drafts, built by
    manager_tendencies.py. Absent is fine and common -- a first-year league has no
    history -- so every consumer treats None as "say nothing"."""
    p = Path(__file__).parent / "data" / "manager_tendencies.json"
    if not p.exists():
        return None
    try:
        return json.load(open(p, encoding="utf-8"))
    except Exception:
        return None


# ⚠ NOT `name.split()[-1]`. Roughly one in twenty draftable players carries a
# generational suffix, so that renders Marvin Harrison Jr. as a chip labelled
# "Jr. · WR" -- and there are three different Jr.s inside the top 80, so the
# label is not just ugly, it is ambiguous. Seen live in a mock at pick 63.
def arc_flag(p) -> str:
    """Compact signal for the board. A HIGH percentile means we are projecting
    ABOVE what comparable players actually did -- a caution, not praise.

    Reads the `arc` field baked into draft_board.json by export_draft_board.py.
    Deliberately NOT computed at runtime: the phone app is a standalone repo and
    cannot import player_history or reach data/player_history.db."""
    if p is None or (isinstance(p, float) and pd.isna(p)):
        return ""
    if p >= 85:
        return f"! {int(p)}"
    if p <= 20:
        return f"+ {int(p)}"
    return str(int(p))


def build_rookie_board(board):
    """Rookie-draft view: rookies only, valued by the REAL dynasty market
    (DynastyProcess superflex value) when available, else our dynasty value.
    Pseudo rookie-ADP = that value's rank (no public rookie-draft ADP feed)."""
    rb = []
    for p in board:
        if not p.get("rookie"):
            continue
        q = dict(p)
        q["pts"] = p.get("dp2") or p.get("dp1") or p.get("dyn") or p.get("pts") or 0.0
        q["rec"] = 0.0
        rb.append(q)
    rb.sort(key=lambda x: -x["pts"])
    for i, q in enumerate(rb, 1):
        q["adp"], q["adp_sd"], q["adp_sf"] = float(i), 3.0 + 0.12 * i, None
    return rb


def revalue_rookies(rb, superflex):
    """Re-rank the rookie board by the DynastyProcess market value that matches the
    league type -- 1QB value (dp1) for single-QB, superflex value (dp2) for SF -- and
    rebuild the pseudo rookie-ADP. In 1QB a top rookie QB (Mendoza) falls behind the
    WRs; in SF he's a premium. Mutates in place (shared with by_id)."""
    for q in rb:
        primary = q.get("dp2") if superflex else q.get("dp1")
        q["pts"] = primary or q.get("dp1") or q.get("dp2") or q.get("dyn") or q.get("pts") or 0.0
    for i, q in enumerate(sorted(rb, key=lambda x: -(x["pts"] or 0.0)), 1):
        q["adp"], q["adp_sd"], q["adp_sf"] = float(i), 3.0 + 0.12 * i, None


board = get_board()
TEND = get_tendencies()
ss = st.session_state
ss.setdefault("drafted", [])          # ordered list of drafted player ids
# The practice room's seed. Generated once per session so it is a number you can
# write down and come back to; "Replay room" reuses it, "New room" rerolls it.
if "room_seed" not in ss:
    ss["room_seed"] = int(np.random.default_rng().integers(1000, 999999))

mode = st.sidebar.radio("Draft type", ["Redraft", "Best Ball", "Rookie (dynasty)"],
                        horizontal=True)
rookie_mode = mode.startswith("Rookie")
bb_mode = mode.startswith("Best Ball")
st.sidebar.checkbox("🎮 Practice (mock draft vs AI)", key="practice",
                    help="AI drafts the other teams by ADP; you make your own picks.")
working = build_rookie_board(board) if rookie_mode else board
by_id = {p["id"]: p for p in working}
key_map = {(norm_name(p["name"]), p["pos"]): p["id"] for p in working}   # for Sleeper/manual matching


def _fold(s: str) -> str:
    """norm_name + accent stripping. Sleeper writes `Audric Estime`, our board has
    `Audric Estimé`, and norm_name does not decompose diacritics -- so the exact
    key misses and the pick becomes a placeholder while he stays on the board as
    available. Used only as a FALLBACK, so it cannot change an exact match."""
    import unicodedata
    return "".join(c for c in unicodedata.normalize("NFKD", norm_name(s))
                   if not unicodedata.combining(c))


# Sleeper identifies a defense by TEAM CODE, not by a name: player_id "SEA",
# first_name "Seattle", last_name "Seahawks", position "DEF", team "SEA". Our
# board calls it "SEA DST", so the name join can never match and every defense
# drafted would land as a placeholder -- in a league that STARTS a DEF, that is
# 12 defenses left showing as available. Match those on the team code instead.
# ⚠ codes drift: Sleeper says LAR for the Rams, our board says LA.
_TEAM_ALIAS = {"LAR": "LA", "STL": "LA", "SD": "LAC", "OAK": "LV", "LVR": "LV",
               "WSH": "WAS", "JAC": "JAX", "ARZ": "ARI", "AZ": "ARI", "GNB": "GB",
               "KAN": "KC", "NWE": "NE", "NOR": "NO", "SFO": "SF", "TAM": "TB"}


def _team_key(t) -> str:
    t = str(t or "").upper().strip()
    return _TEAM_ALIAS.get(t, t)


fold_map = {}
for _p in working:                       # first writer wins, so exact stays exact
    fold_map.setdefault((_fold(_p["name"]), _p["pos"]), _p["id"])
dst_map = {_team_key(_p.get("team")): _p["id"] for _p in working if _p["pos"] == "DST"}


# --------------------------------------------------------------------------- helpers
def draft_ids(ids):
    for pid in ids:
        if pid and pid not in ss.drafted:
            ss.drafted.append(pid)


def undo():
    if ss.drafted:
        ss.drafted.pop()
        # keep the "gone since your last pick" window inside the draft
        ss["last_my_pick"] = min(int(ss.get("last_my_pick") or 0), len(ss.drafted))


SLEEPER_USER_ID = "430840397841838080"   # PennerBoy -- auto-detect your draft slot from draft_order


def sleeper_sync(draft_id: str = None, league_id: str = None):
    """Pull picks + config (type->snake, your slot, the LIVE starting lineup) +
    board metadata (team names, traded picks) from Sleeper. Accepts a draft_id OR
    a league_id."""
    from sleeper_api import league_state
    stt = league_state(league_id=league_id, draft_id=(draft_id or "").strip() or None)
    ci = {"type": stt["type"], "snake": stt["snake"], "teams": stt["teams"],
          "rounds": stt["rounds"], "my_slot": stt["my_slot"],
          "roster_cfg": stt.get("roster_cfg") or {}, "status": stt.get("status"),
          "league_name": stt.get("league_name"), "pick_timer": stt.get("pick_timer")}
    drafted, matched, missed = [], [], []
    for pk in stt["picks"]:
        m = pk.get("metadata") or {}
        nm = f"{m.get('first_name','')} {m.get('last_name','')}".strip()
        pos = pos_norm(m.get("position"))
        if pos == "DST":                              # matched by team, never by name
            pid = dst_map.get(_team_key(m.get("team") or pk.get("player_id")))
        else:
            pid = (key_map.get((norm_name(nm), pos))
                   or fold_map.get((_fold(nm), pos)))
        if pid:
            drafted.append(pid); matched.append(pid)
        else:
            # keep the slot occupied so pick numbers / whose-turn stay aligned (e.g. IDP
            # picks our offense-only board doesn't carry)
            drafted.append(f"__off_{pk.get('pick_no')}")
            missed.append(f"{nm} ({pos})")
    ss.drafted = drafted
    ss["sleeper_cfg"] = ci
    ss["sleeper_state"] = stt
    return len(matched), missed, ci


def sleeper_pick_count(league_id=None, draft_id=None) -> int | None:
    """Just the pick COUNT -- one small GET, for the auto-sync poller. Deliberately
    separate from sleeper_sync: polling the full league_state every few seconds
    would be 5 requests a tick, and the only question is 'did anything change'."""
    import requests
    try:
        if not draft_id:
            from sleeper_api import resolve_draft_id
            draft_id = resolve_draft_id(league_id)
        r = requests.get(f"https://api.sleeper.app/v1/draft/{draft_id}/picks", timeout=8)
        r.raise_for_status()
        return len(r.json() or [])
    except Exception:
        return None          # a blip must never break the draft screen


def total_picks():
    return cfg.teams * cfg.total_rounds()


def do_pick(pid):
    """Commit a pick; in practice mode, let the AI draft the other teams up to your next pick."""
    if len(ss.drafted) >= total_picks():      # the draft has a last pick
        return
    draft_ids([pid])
    ss["last_my_pick"] = len(ss.drafted)      # where the "since your pick" feed starts
    # With auto-advance off the room does NOT jump to your next turn, so the
    # step controls have something to step: otherwise every pick lands you back
    # on the clock and "one pick" is always a no-op.
    if st.session_state.get("practice") and ss.get("auto_adv", True):
        ss.drafted = mock_advance(prep_valued(working, cfg), cfg, ss.drafted,
                                 None, seed=ss['room_seed'])


def team_roster(slot):
    """[(overall, player)] for one drafting slot, in pick order."""
    out = []
    for i, pid in enumerate(ss.drafted):
        if team_on_clock(cfg, i + 1) == slot:
            p = by_id.get(pid)
            if p:
                out.append((i + 1, p))
    return out


def seat_name(slot):
    return slot_team(cfg, ss.get("sleeper_state"), slot)


# --------------------------------------------------------------------------- sidebar: league
with st.sidebar:
    st.header("🏈 League setup")
    preset = st.selectbox("Quick league", ["Custom"] + list(ALL_PRESETS),
                          help="Your real leagues (from Sleeper/ESPN) + generic setups, or Custom.")
    teams = st.number_input("Teams", 4, 16, 12)
    if bb_mode:
        # Best ball has no lineup decision and no waiver wire, so the strategy
        # archetypes (which are about how you SEQUENCE a startable roster) do
        # not apply -- value comes from bestball.py instead. Scoring is DK.
        scoring, superflex, archetype = "ppr", False, "value"
        st.caption("**DraftKings Best Ball** — 20 rounds, QB/2RB/3WR/TE/FLEX, "
                   "no K or DST. Players are valued by what they add to your "
                   "**optimal weekly lineup**, so bench depth, ceiling and bye "
                   "coverage all count.")
    elif not rookie_mode:
        scoring = st.selectbox("Scoring", ["ppr", "half", "standard"],
                               format_func=lambda s: {"ppr": "PPR", "half": "Half-PPR", "standard": "Standard"}[s])
        superflex = st.checkbox("Superflex (2 QB slots)")
        archetype = st.selectbox("Strategy", ARCHETYPES, format_func=lambda a: ARCHETYPE_LABEL[a],
                                 help="Best value = fully reactive (VOR + run-aware). Others commit to a structural plan.")
    else:
        scoring, superflex, archetype = "ppr", False, "value"
        r_rounds = st.number_input("Rookie draft rounds", 1, 8, 5)
        r_linear = st.checkbox("Linear draft (not snake)")
        st.caption("Rookies valued by dynasty value; pseudo-ADP = dynasty rank (no public rookie ADP yet).")
    my_slot = st.number_input("Your draft slot", 1, int(teams), 1)
    _d = DK_BESTBALL["starters"] if bb_mode else {}
    with st.expander("Starting lineup / bench"):
        c1, c2 = st.columns(2)
        n_qb = c1.number_input("QB", 0, 3, _d.get("QB", 1))
        n_rb = c2.number_input("RB", 0, 4, _d.get("RB", 2))
        n_wr = c1.number_input("WR", 0, 4, _d.get("WR", 2))
        n_te = c2.number_input("TE", 0, 3, _d.get("TE", 1))
        n_fx = c1.number_input("FLEX", 0, 3, _d.get("FLEX", 1))
        n_sf = c2.number_input("SUPERFLEX", 0, 2, 1 if superflex else 0)
        n_k = c1.number_input("K", 0, 2, _d.get("K", 1))
        n_dst = c2.number_input("DST", 0, 2, _d.get("DST", 1))
        bench = st.number_input("Bench", 0, 15, 12 if bb_mode else 6)
    starters = {"QB": n_qb, "RB": n_rb, "WR": n_wr, "TE": n_te,
                "FLEX": n_fx, "SUPERFLEX": n_sf, "K": n_k, "DST": n_dst}
    if bb_mode:
        cfg = LeagueConfig(teams=int(teams), scoring="ppr", superflex=False,
                           starters=starters, bench=int(bench), my_slot=int(my_slot),
                           snake=True, rounds=int(DK_BESTBALL["rounds"]),
                           archetype="value", best_ball=True)
    elif rookie_mode:
        cfg = LeagueConfig(teams=int(teams), scoring="ppr", starters=starters, bench=int(bench),
                           my_slot=int(my_slot), snake=not r_linear, rounds=int(r_rounds),
                           archetype="value")
    else:
        cfg = LeagueConfig(teams=int(teams), scoring=scoring, superflex=superflex,
                           starters=starters, bench=int(bench), my_slot=int(my_slot),
                           archetype=archetype)
    if preset != "Custom":                                # a quick-league preset defines the league
        P = ALL_PRESETS[preset]
        st_p = P.get("starters", starters)
        slot_p = min(int(my_slot), int(P["teams"]))
        if rookie_mode:
            cfg = LeagueConfig(teams=int(P["teams"]), scoring="ppr", superflex=P.get("superflex", False),
                               starters=st_p, bench=int(P.get("bench", bench)), my_slot=slot_p,
                               snake=P.get("snake", not r_linear), rounds=int(P.get("rounds", r_rounds)), archetype="value")
        else:
            cfg = LeagueConfig(teams=int(P["teams"]), scoring=P.get("scoring", "ppr"),
                               superflex=P.get("superflex", False), starters=st_p,
                               bench=int(P.get("bench", bench)), my_slot=slot_p,
                               snake=P.get("snake", True), archetype=archetype,
                               rounds=(int(P["rounds"]) if P.get("rounds") else None),
                               best_ball=bool(P.get("best_ball", False)))
        if P.get("kind") == "rookie" and not rookie_mode:
            st.info("Dynasty rookie league — set **Draft type → Rookie** at the top.")
        elif P.get("kind") == "bestball" and not bb_mode:
            st.info("Best-ball league — set **Draft type → Best Ball** at the top.")
        elif P.get("kind") == "redraft" and rookie_mode:
            st.info("Redraft league — set **Draft type → Redraft** at the top.")

    # ⭐ THE LIVE LEAGUE IS AUTHORITATIVE, NOT THE PRESET.
    # A preset is a snapshot taken whenever import_leagues.py last ran; commissioners
    # edit leagues. ReDrafters Rejoice was imported 2026-08-06 as 12T **Superflex**
    # / 16 rounds and by 2026-08-21 had no SUPER_FLEX slot and 15 rounds. Superflex
    # moves QB replacement from ~QB12 to ~QB24, so under the stale preset Josh Allen
    # read VOR 149 / board slot 6 instead of VOR 38 / slot 47 -- a round-1 QB
    # recommendation in a single-QB league, with nothing anywhere reporting an error.
    # So once you sync, everything the league object knows overrides the widgets.
    _sc = ss.get("sleeper_cfg")
    _drift = []
    if _sc:
        if _sc.get("snake") is not None and bool(_sc["snake"]) != cfg.snake:
            _drift.append(f"draft type → {'snake' if _sc['snake'] else 'linear'}")
        if _sc.get("snake") is not None:
            cfg.snake = bool(_sc["snake"])
        if _sc.get("my_slot"):
            cfg.my_slot = int(_sc["my_slot"])
        if _sc.get("teams"):
            cfg.teams = int(_sc["teams"])
        _rc = _sc.get("roster_cfg") or {}
        if _rc.get("starters") and not bb_mode:
            if _rc["starters"] != cfg.starters:
                _drift.append("starting lineup")
            cfg.starters = dict(_rc["starters"])
            if bool(_rc.get("superflex")) != bool(cfg.superflex):
                _drift.append(f"superflex → {'ON' if _rc.get('superflex') else 'OFF'}")
            cfg.superflex = bool(_rc.get("superflex"))
            if _rc.get("bench") is not None:
                cfg.bench = int(_rc["bench"])
            if _rc.get("scoring") and _rc["scoring"] != cfg.scoring:
                _drift.append(f"scoring → {_rc['scoring']}")
                cfg.scoring = _rc["scoring"]
        # the DRAFT's own round count is authoritative in every mode -- the league's
        # settings.draft_rounds is frequently absent or stale (here: 3, for 15 rounds)
        if _sc.get("rounds") and not bb_mode:
            if int(_sc["rounds"]) != int(cfg.total_rounds()):
                _drift.append(f"rounds → {int(_sc['rounds'])}")
            cfg.rounds = int(_sc["rounds"])
        ss["cfg_drift"] = _drift
        # ⚠ .strip(): Sleeper league names can carry a trailing space
        # ("ReDrafters Rejoice "), and markdown will not close a bold run when the
        # closing ** is preceded by whitespace -- the live app rendered the
        # asterisks literally.
        st.caption(f"📲 **{(_sc.get('league_name') or 'Sleeper').strip()}** · {_sc.get('type', '?')} · "
                   f"slot {cfg.my_slot} · {cfg.total_rounds()} rds · "
                   + ("SUPERFLEX" if cfg.superflex else "1QB"))

    st.divider()
    st.subheader("🔄 Sleeper live-sync")
    _sl = {p["name"]: p["league_id"] for p in ALL_PRESETS.values()
           if p.get("source") == "sleeper" and p.get("league_id")}
    lg = st.selectbox("My Sleeper leagues", ["—"] + list(_sl),
                      help="Loads that league's current draft automatically — no draft ID needed.")
    if st.button("📲 Load this league's draft", width="stretch", type="primary") and lg != "—":
        try:
            n, missed, ci = sleeper_sync(league_id=_sl[lg])
            ss["started"] = True
            st.success(f"{lg}: {n} picks · {ci.get('type', '?')} · slot {ci.get('my_slot', '?')}")
            if missed:
                st.caption("Unmatched (IDP/UDFA): " + ", ".join(missed[:6]))
            st.rerun()
        except Exception as e:
            st.error(f"Load failed: {e}")
    if ss.get("sleeper_cfg"):
        if st.button("🔁 Refresh picks", width="stretch",
                     help="Re-pull the picks made since you last synced."):
            try:
                _lid = (ss.get("sleeper_state") or {}).get("league_id")
                _did = (ss.get("sleeper_state") or {}).get("draft_id")
                n, missed, ci = sleeper_sync(league_id=_lid, draft_id=None if _lid else _did)
                st.success(f"{n} picks")
                st.rerun()
            except Exception as e:
                st.error(f"Refresh failed: {e}")
    with st.expander("…or paste a Draft ID"):
        did = st.text_input("Draft ID", help="sleeper.com/draft/nfl/<DRAFT_ID>")
        if st.button("Pull picks", width="stretch") and did:
            try:
                n, missed, ci = sleeper_sync(draft_id=did)
                ss["started"] = True
                st.success(f"Synced {n} picks · {ci.get('type', '?')}")
                st.rerun()
            except Exception as e:
                st.error(f"Sync failed: {e}")

    st.divider()
    if st.button("↩︎ Undo last pick", width="stretch"):
        undo(); st.rerun()
    if st.button("🗑 Reset draft", width="stretch"):
        ss.drafted = []; ss.pop("plan", None); ss.pop("sleeper_cfg", None); ss.pop("sleeper_state", None)
        ss.pop("cfg_drift", None)
        ss["last_my_pick"] = 0; ss["started"] = False; st.rerun()


# rookie board: re-rank by the market value matching the league type (1QB vs superflex)
if rookie_mode:
    revalue_rookies(working, cfg.superflex)

# --------------------------------------------------------------------------- start gate
ss.setdefault("started", False)
if not ss["started"]:
    st.title("🏈 Draft Wizard")
    _sf = " Superflex" if cfg.superflex else ""
    _summ = f"**{mode}** · {cfg.teams}-team {cfg.scoring.upper()}{_sf} · your slot **{cfg.my_slot}** · {cfg.total_rounds()} rounds"
    if ss.get("practice"):
        _summ += f" · 🎮 practice vs AI · room **#{ss['room_seed']}**"
    st.info(_summ)
    st.caption(f"Board: **{len(working)}** players · "
               f"**{sum(1 for p in working if p.get('adp'))}** with live ADP")
    if st.button("▶ Start draft", type="primary", width="stretch"):
        ss.drafted = []
        ss.pop("plan", None)
        ss["last_my_pick"] = 0
        if ss.get("practice"):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None, seed=ss['room_seed'])
        ss["started"] = True
        st.rerun()
    st.caption("Set your league, strategy, slot, and Redraft/Rookie + Practice in the sidebar "
               "(☰ top-left), then hit Start. **For a real Sleeper draft, use "
               "“Load this league's draft” instead** — it reads your slot, the draft "
               "type, the true round count and the live starting lineup from Sleeper.")
    st.stop()

# --------------------------------------------------------------------------- analyze
res = analyze(working, cfg, ss.drafted,
              seed=(ss["room_seed"] if ss.get("practice") else None))
on_clock_me = res["on_clock"] == cfg.my_slot
done = res["complete"]
sstate = ss.get("sleeper_state")

# --------------------------------------------------------------------------- status bar
st.markdown(status_bar_html(cfg, sstate, res, seat_name(res["on_clock"])),
            unsafe_allow_html=True)

# --------------------------------------------------------------------------- auto-sync
# A 15-round 12-team draft is 180 picks. Tapping Sync after each one is not a
# workflow, so poll Sleeper on a timer and rerun ONLY when the pick count actually
# moves. Failure here must be invisible: a dropped request returns None and the
# board simply stays on the last good state.
if sstate and not done:
    _as = st.session_state.get("auto_sync", False)
    if _as:
        @st.fragment(run_every="12s")
        def _poll():
            n = sleeper_pick_count(league_id=sstate.get("league_id"),
                                   draft_id=sstate.get("draft_id"))
            if n is None:
                st.caption("🔌 Sleeper didn't answer — retrying; the board below is "
                           "the last good state.")
                return
            if n != len(ss.drafted):
                try:
                    sleeper_sync(league_id=sstate.get("league_id"))
                except Exception:
                    return
                st.rerun(scope="app")
            st.caption(f"🔄 auto-syncing every 12s · {n} picks in")
        _poll()

if ss.get("cfg_drift"):
    st.warning("⚠︎ Your saved preset disagreed with the live league — Sleeper wins: **"
               + "**, **".join(ss["cfg_drift"]) + "**. "
               "Re-run `import_leagues.py` to update the preset.")

# --------------------------------------------------------------------------- draft controls
uc = st.columns([1, 1, 1, 1.4])
if uc[0].button("↩︎ Undo", width="stretch"):
    undo(); st.rerun()
if uc[1].button("🗑 Reset", width="stretch"):
    ss.drafted = []; ss.pop("plan", None); ss.pop("sleeper_cfg", None)
    ss.pop("sleeper_state", None); ss.pop("cfg_drift", None); ss["started"] = False; st.rerun()
if sstate:
    if uc[2].button("🔁 Sync", width="stretch", type="primary",
                    help="Pull the latest picks from Sleeper now"):
        try:
            sleeper_sync(league_id=sstate.get("league_id"))
            st.rerun()
        except Exception as e:
            st.error(f"Sync failed: {e}")
    uc[3].toggle("🔄 Auto-sync", key="auto_sync", value=False,
                 help="Poll Sleeper every 12s and pull picks automatically. "
                      "Turn it on when the draft starts.")
st.progress(min(1.0, len(ss.drafted) / max(1, res["total_picks"])),
            text=f"{len(ss.drafted)} of {res['total_picks']} picks made · "
                 f"round {res['round']} of {cfg.total_rounds()}")

# --------------------------------------------------------------------------- practice controls
if st.session_state.get("practice"):
    with st.expander("🎮 Practice controls", expanded=not done):
        pc = st.container()
        pc.caption(f"AI drafts the other {cfg.teams - 1} teams off ADP; you pick your own.")
        pcc = pc.columns(4)
        if pcc[0].button("▶ Sim to my pick", width="stretch", disabled=done):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, ss.drafted,
                                 None, seed=ss['room_seed'])
            st.rerun()
        if pcc[1].button("⏱ One pick", width="stretch", disabled=done or on_clock_me,
                         help="Advance the room a single pick so you can watch it develop. "
                              "Needs auto-advance off, otherwise the room is already at your turn."):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, ss.drafted,
                                      None, max_picks=1, seed=ss["room_seed"])
            st.rerun()
        if pcc[2].button("🔄 Replay room", width="stretch",
                         help="Start over against the SAME opponents. Make different "
                              "picks and you can see what the other build would have "
                              "got you."):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None, seed=ss['room_seed'])
            ss.pop("plan", None); ss["last_my_pick"] = 0
            st.rerun()
        _auto = pcc[3].button("⏭ Auto-draft rest", width="stretch", disabled=done,
                              help="AI finishes the whole draft, picking your team by your Strategy")
        pc.checkbox("Auto-advance to my next pick", key="auto_adv", value=True,
                    help="Off = the room stays where it is after you pick, so you can step "
                         "through the other teams one pick at a time.")
        # ⭐ The room seed, exposed so a practice draft is repeatable. Without it
        # every mock draws a fresh room (measured: 12/12 distinct pick orders,
        # though 88% the same players early), which makes it impossible to ask
        # "what would zero-RB have got me against THAT draft?" -- the thing you
        # most want practice for.
        sc = pc.columns([2, 1, 3])
        # ⚠ the key must carry the seed. With a FIXED key the widget's persisted
        # value wins the next rerun, so "New room" set a fresh seed, rerendered,
        # and this input immediately wrote the OLD one back -- the button looked
        # dead. Streamlit will not let you assign a widget's key after it is
        # instantiated, so the fix is a key that changes with the value.
        _new_seed = sc[0].number_input("Room seed", 1, 999999, int(ss["room_seed"]),
                                       step=1, key=f"seed_input_{ss['room_seed']}",
                                       help="Same seed = the same opponents behaving the "
                                            "same way. Write it down to come back to a "
                                            "room, or type a friend's to draft the same one.")
        if int(_new_seed) != int(ss["room_seed"]):
            ss["room_seed"] = int(_new_seed)
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None,
                                      seed=ss["room_seed"])
            ss.pop("plan", None); ss["last_my_pick"] = 0
            st.rerun()
        sc[1].write("")
        if sc[1].button("🎲 New room", width="stretch",
                        help="Roll a different set of opponents."):
            ss["room_seed"] = int(np.random.default_rng().integers(1000, 999999))
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None,
                                      seed=ss["room_seed"])
            ss.pop("plan", None); ss["last_my_pick"] = 0
            st.rerun()
        sc[2].caption(f"Room **#{ss['room_seed']}** — “Replay room” restarts this exact "
                      f"draft, so you can try a different strategy against the same "
                      f"opponents and compare.")
        # a fixed slot inside the practice panel, written to from the loop below --
        # auto-drafting a full board runs a Monte-Carlo per remaining round, which is
        # several seconds of silence otherwise
        prog = pc.empty()
        if _auto:
            valued = prep_valued(working, cfg)
            total = total_picks(); guard = 0
            while len(ss.drafted) < total and guard < total + 5:
                ss.drafted = mock_advance(valued, cfg, ss.drafted, None,
                                          seed=ss["room_seed"])
                if len(ss.drafted) >= total:
                    break
                # a cheaper sim than the on-screen default: this runs once per remaining
                # round, and the pick only needs the ranking, not 4-digit survival odds
                _r = analyze(working, cfg, ss.drafted, n_sims=300,
                             seed=ss["room_seed"]).get("recommendation")
                if not _r:
                    break
                ss.drafted.append(_r["id"]); guard += 1
                prog.progress(min(1.0, len(ss.drafted) / total),
                              text=f"Auto-drafting… {len(ss.drafted)}/{total}")
            st.rerun()

# --------------------------------------------------------------------------- draft complete
if done:
    g = grade_draft(cfg, ss.drafted, working)
    _seed = ss["room_seed"] if ss.get("practice") else None
    if ss.get("review_for") != len(ss.drafted):
        ss["review"] = DR.review(working, cfg, ss.drafted, seed=_seed)
        ss["review_for"] = len(ss.drafted)
        # log it once per completed draft
        ss.setdefault("mock_history", MH.merge(MH.load_disk(), []))
        if ss.get("practice"):
            ss["mock_history"] = MH.merge(ss["mock_history"],
                                          [MH.record(cfg, _seed, g["grade"], ss["review"], mode)])
            ss["hist_saved"] = MH.save_disk(ss["mock_history"])
    rv = ss["review"]

    fin = st.container(border=True)
    fin.markdown(f"### 🏁 Draft complete — {res['total_picks']} picks over {cfg.total_rounds()} rounds"
                 + (f"  ·  room **#{_seed}**" if _seed else ""))
    fm = fin.columns(4)
    fm[0].metric("Your grade", g["grade"])
    fm[1].metric("Finish", f"{rv['rank']} of {rv['teams']}")
    fm[2].metric("Value banked", f"{rv['grade_value']}",
                 delta=f"{rv['edge']:+d} vs league avg")
    fm[3].metric("Avg vs ADP", f"{rv['avg_vs_adp']:+.1f}" if rv["avg_vs_adp"] is not None else "—",
                 help="Mean (pick number − that player's ADP) across your picks. "
                      "Positive = the room let players fall to you; negative = you reached.")

    fin.markdown("**Where you gained and lost it**")
    _pr = pd.DataFrame([{"Pos": r["pos"], "You": r["n"], "Your value": r["value"],
                         "League avg": r["league_avg"], "Edge": r["edge"],
                         "Your best": r["best"]} for r in rv["positions"]])
    fin.dataframe(_pr, hide_index=True, width="stretch")
    _note = DR.position_note(rv)
    if _note:
        fin.caption(_note)

    if rv.get("replayable"):
        fin.markdown(f"**💡 Where you left value** — {DR.headline(rv)}")
        if rv["misses"]:
            for m in rv["misses"]:
                fin.markdown("- " + DR.miss_sentence(m))
        fin.caption(
            "These are **exact, not estimated**: for each one the room was REPLAYED "
            "from that pick with the other player in your seat and the same seed, so "
            "“he was still there” is something that actually happened in an "
            "alternative draft rather than a survival guess. ⚠ It is still hindsight "
            "— you only know who went where afterwards — so read it as a drill, not a "
            "scorecard. Only misses worth ≥12 VOR are shown, and value below "
            "replacement is floored at zero (a bench body you would never start is "
            "worth 0, not −30).")
    else:
        fin.caption("Run this as a **practice** mock to get the “where you left value” "
                    "review — it needs the room's seed to replay the counterfactual.")

    if st.session_state.get("practice"):
        fc = fin.columns(2)
        if fc[0].button("🔄 Replay this room", type="primary", key="again", width="stretch",
                        help="Same opponents, same seed — try a different strategy."):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None, seed=ss["room_seed"])
            ss.pop("plan", None); ss.pop("review", None); ss.pop("review_for", None)
            ss["last_my_pick"] = 0
            st.rerun()
        if fc[1].button("🎲 New room", key="again_new", width="stretch"):
            ss["room_seed"] = int(np.random.default_rng().integers(1000, 999999))
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], None, seed=ss["room_seed"])
            ss.pop("plan", None); ss.pop("review", None); ss.pop("review_for", None)
            ss["last_my_pick"] = 0
            st.rerun()

# --------------------------------------------------------------------------- THE PICK
rec = res["recommendation"]
main, side = st.columns([3, 2], gap="medium")

with main:
    if on_clock_me and not done:
        st.success("🟢 **You're on the clock**")
    if rec:
        surv = rec["survival"] * 100
        _c = POS_BG.get(rec["pos"], "#475569")
        st.markdown(
            f'<div class="dw-rec">'
            f'<h3>⭐ {rec["name"]} '
            f'<span class="dw-pill" style="background:{_c}">{rec["pos"]}{rec["posrank"]}</span>'
            f'<span style="color:#94a3b8;font-size:13px;font-weight:400">{rec["team"] or ""}</span></h3>'
            f'<div style="color:#e2e8f0;font-size:13px">'
            f'<b>VOR {rec["vor"]:.0f}</b> &nbsp;·&nbsp; Tier {rec["pos"]}T{rec["tier"]} '
            f'({rec["tier_left"]} left in tier) &nbsp;·&nbsp; '
            f'survives to your pick <b>{surv:.0f}%</b></div>'
            f'<div class="dw-sub">➡︎ <i>{rec["reason"]}</i></div></div>',
            unsafe_allow_html=True)
        if on_clock_me:
            if st.button(f"✅ Draft {rec['name']}", width="stretch", type="primary"):
                do_pick(rec["id"]); st.rerun()
        else:
            st.caption(f"🎯 Your target for pick {pick_label(cfg, res['my_next_pick'])} "
                       f"(#{res['my_next_pick']}). ⏳ **{seat_name(res['on_clock'])}** is on the "
                       f"clock — tap who they take below.")


with side:
    # nobody is on the clock once the last pick is in -- the panel used to show
    # "15.12 ON THE CLOCK" on a completed draft
    # tendencies only mean something once seats are tied to real Sleeper managers
    _tend = TEND if (sstate and TEND
                     and str(TEND.get("league_id")) == str(sstate.get("league_id"))) else None
    if not done:
        st.markdown('<div class="dw-h">🕐 On deck — who picks before you</div>',
                    unsafe_allow_html=True)
        st.markdown(on_deck_html(cfg, sstate, res["current_overall"], res["my_next_pick"],
                                 res["opponents"].get("seat_need"), max_rows=13,
                                 complete=done, tendencies=_tend),
                    unsafe_allow_html=True)
        if _tend:
            _fc = _tend.get("format_changed_from") or []
            st.caption(
                f"↳ lines are what that manager has actually done across "
                f"{len(_tend.get('seasons_used') or [])} past drafts in **this** league, "
                f"picked for the round you're in."
                + (f" ⚠ **{', '.join(_fc)} were "
                   f"{'1QB' if _tend['format_now'].get('superflex') else 'SUPERFLEX'} and "
                   f"{_tend.get('season_now')} is "
                   f"{'SUPERFLEX' if _tend['format_now'].get('superflex') else '1QB'}** — "
                   f"QB timing from those years is excluded, and expect this room to "
                   f"reach on QBs out of habit." if _fc else ""))

# --------------------------------------------------------------------------- quick mark
# A tap always books the pick for whoever is ON THE CLOCK, and the two cases want
# DIFFERENT shortlists:
#   on the clock  -> your best options, i.e. the decision order
#   off the clock -> who the room is most likely to take next, i.e. ADP
# (the original used raw VOR for both, which offered a kicker in round 7)
# ⚠ full width, NOT inside the recommendation column: at a 958px window that
# column is ~277px and five stretched buttons ellipsised every surname to "R..".
if rec and not done:
    if on_clock_me:
        shortlist, chip_note = res["ranked"][:5], "your pick"
    else:
        shortlist = sorted([p for p in res["best_available"] if p.get("adp")],
                           key=lambda x: x["adp"])[:5]
        chip_note = f"who {seat_name(res['on_clock'])} took — likeliest by ADP"
    st.markdown(f'<div class="dw-h">Quick mark — {chip_note}</div>',
                unsafe_allow_html=True)
    chips = st.columns(len(shortlist) or 1)
    for i, a in enumerate(shortlist):
        if chips[i].button(f"{surname(a['name'])} · {a['pos']}", key=f"chip_{i}",
                           width="stretch",
                           help=f"{a['name']} · {a['pos']}{a.get('posrank','')} "
                                f"· {a.get('team') or ''}"):
            do_pick(a["id"]); st.rerun()

st.divider()

# --------------------------------------------------------------------------- best available
# Full width on purpose. This table is the product -- 12 columns inside a 3:2
# column split gives each one ~50px, which turns the numbers you draft off into a
# horizontal scroll. The rails below it are things you glance at, not read.
if True:
    bh = st.columns([2, 3])
    bh[0].subheader("Best available")
    # ⭐ THE ORDERING IS A CHOICE AND IT HAS TO BE VISIBLE.
    # `ranked` = the wizard's own decision order (effective VOR + scarcity + need,
    # roster-aware). `best_available` = raw positional VOR, roster-blind. They can
    # disagree completely: at pick 73 of a 15-round league Brandon Aubrey is VOR
    # 39.4 (2nd on the raw board) and _rec_score -28.0 (below every startable
    # player). Showing the raw order as "best available" put a kicker second on
    # the screen you draft from. Default to the order the pick is actually made on.
    _ORDERS = {"⭐ For me": "ranked", "Raw value": "best_available", "Market ADP": "market"}
    _pick_order = bh[1].radio("Rank by", list(_ORDERS), horizontal=True,
                              label_visibility="collapsed", key="rank_by",
                              help="For me = the wizard's own ranking (your roster, tier "
                                   "cliffs and position runs priced in). Raw value = best "
                                   "player left, ignoring your roster. Market ADP = the "
                                   "order the room is likely to take them.")
    _which = _ORDERS[_pick_order]
    # Position filter. Only offer positions this league actually uses -- a K chip
    # in a league with no kicker slot is a control that can only mislead. FLEX is
    # a convenience for RB/WR/TE together, which is the filter you actually want
    # when you are deciding who fills a flex spot.
    _used = [q for q in ("QB", "RB", "WR", "TE")
             if cfg.starters.get(q) or cfg.starters.get("FLEX") or cfg.superflex]
    _used += [q for q in ("K", "DST") if cfg.starters.get(q)]
    _opts = _used[:4] + (["FLEX"] if cfg.starters.get("FLEX") else []) + _used[4:]
    _posf = bh[1].pills("Positions", _opts, selection_mode="multi",
                        label_visibility="collapsed", key="posfilter",
                        help="Filter the board. Nothing selected = every position. "
                             "FLEX = RB/WR/TE together.")
    # On a phone the table is ~343px wide. 13 columns there is a horizontal scroll
    # with the player's NAME scrolled off, which makes the numbers unreadable --
    # so Player is pinned (below) and this drops to the six columns you actually
    # draft off. Not auto-detected: Streamlit renders server-side and has no
    # viewport width, so guessing would be wrong on a tablet either way.
    _tg = bh[1].columns(2)
    _compact = _tg[0].toggle("Compact", value=False, key="compact_cols",
                             help="Fewer columns — fits a phone screen without scrolling.")
    # The experts already move our value through `ecr_pos_rank`; this shows the
    # disagreement instead of only absorbing it, which is the "am I missing
    # something?" read. Off by default -- four more columns is a lot on a phone.
    _experts = _tg[1].toggle("Experts", value=False, key="expert_cols",
                             help="Add JJ Zachariason, Justin Boone, Mike Clay and "
                                  "WalterFootball's POSITIONAL ranks. They already "
                                  "feed our consensus; this shows where they disagree "
                                  "with it.")
    if _which == "market":
        _pool = (sorted([p for p in res["best_available"] if p.get("adp")],
                        key=lambda x: x["adp"])
                 + [p for p in res["best_available"] if not p.get("adp")])
    else:
        _pool = res[_which]
    if _posf:
        _want = set()
        for _x in _posf:
            _want |= {"RB", "WR", "TE"} if _x == "FLEX" else {_x}
        # build from the PER-POSITION windows, not by filtering the top-60 --
        # see the note on `by_pos` in draft_engine.analyze
        _pool = [p for pos in _want for p in res["by_pos"].get(pos, [])]
        if _which == "market":
            _pool.sort(key=lambda x: (x.get("adp") is None, x.get("adp") or 0))
        elif _which == "best_available":
            _pool.sort(key=lambda x: -(x.get("vor") or 0))
        else:
            _pool.sort(key=lambda x: -(x.get("rec_score") or 0))
    rows = []
    _cur = res["current_overall"]
    for p in _pool[:60]:
        _adp = p.get("adp")
        rows.append({
            "Player": p["name"], "Pos": f"{p['pos']}{p['posrank']}", "Tm": p.get("team"),
            "Bye": p.get("bye"),
            # Score IS the pick. VOR is only one of its three terms, so a board that
            # shows VOR alone hides why a 3rd TE or an early kicker is not the pick.
            "Score": p.get("rec_score"),
            "VOR": p["vor"], "Tier": f"{p['pos']}T{p['tier']}" if p.get("tier") else "",
            # In best ball the pick is made on MARGINAL VALUE, not VOR. Showing
            # only VOR would display one number while deciding on another --
            # BB is the points he adds to your optimal weekly lineups, and Edge
            # is that minus the man you would get at his position instead,
            # which is what the board is actually sorted by.
            **({"BB": p.get("bb"),
                "Edge": (None if p.get("bb") is None
                         else round(p["bb"] - (p.get("bb_repl") or 0.0)))}
               if bb_mode else {}),
            "Surv%": round((p.get("survival") or 1) * 100),
            "ADP": _adp,
            # how far past his own ADP he has already fallen. Positive = the market
            # would have taken him by now and has not, i.e. he is on sale AT THIS
            # PICK. This is the number a room reads out loud ("he's 20 picks past
            # ADP"), and it is not derivable from the ADP column alone mid-draft.
            "vsADP": (None if _adp is None else round(_cur - _adp)),
            "CoW": p.get("cost_of_waiting"),
            # Arc  = where OUR projection sits inside the comp distribution
            # Decl% = share of those comps who fell off >25% the next year
            # Both are needed: at the top of the board almost everyone reads high
            # on Arc (we project elite production, comps regress), so Arc alone
            # does not discriminate. Lamb is 90th with 5% declining; McCaffrey is
            # 100th with 100% declining. The pair is the signal.
            "Arc": arc_flag(p.get("arc")),
            "Decl%": p.get("decl"),
            **({"JJ": p.get("jj"), "Boone": p.get("boone"),
                "Clay": p.get("clay"), "Walt": p.get("walt")} if _experts else {}),
        })
    if not rows:
        st.info(f"No {', '.join(_posf)} left on the board.")
        st.stop()
    df = pd.DataFrame(rows)
    # ⚠ a column with ANY None becomes object dtype, and Styler's `na_rep` only
    # replaces NaN -- so a player with no ADP rendered the literal string "None"
    # in ADP and vsADP on the live board. Coerce first; then None becomes NaN and
    # na_rep works. Same root cause as `Bye`: a display path that is fine until
    # one row is missing.
    for _c in ("Bye", "Score", "VOR", "Surv%", "ADP", "vsADP", "CoW", "Decl%",
               "BB", "Edge", "JJ", "Boone", "Clay", "Walt"):
        if _c in df.columns:
            df[_c] = pd.to_numeric(df[_c], errors="coerce")
    if _compact:
        _keep = ["Player", "Pos", "Score", "Tier", "Surv%", "vsADP"]
        if bb_mode:
            _keep = ["Player", "Pos", "BB", "Edge", "Surv%", "vsADP"]
        df = df[[c for c in _keep if c in df.columns]]
    _grad = "Edge" if (bb_mode and "Edge" in df.columns) else "Score"
    _fmt = {"Score": "{:.0f}", "VOR": "{:.0f}", "ADP": "{:.0f}", "CoW": "{:.0f}",
            "Surv%": "{:.0f}", "Decl%": "{:.0f}", "vsADP": "{:+.0f}", "Bye": "{:.0f}",
            "JJ": "{:.0f}", "Boone": "{:.0f}", "Clay": "{:.0f}", "Walt": "{:.0f}"}
    if bb_mode:
        _fmt.update({"BB": "{:.0f}", "Edge": "{:.0f}"})
    def _grad_ok(col):
        """A gradient needs SPREAD. On a constant column matplotlib maps every
        cell to the bottom of the colormap, so a post-draft board where every
        Surv% is 100 rendered solid dark red -- reading as 'nobody survives' when
        it means the opposite."""
        if col not in df.columns:
            return False
        v = pd.to_numeric(df[col], errors="coerce").dropna()
        return len(v) > 1 and v.nunique() > 1

    sty = df.style
    if _grad_ok(_grad):
        sty = sty.background_gradient(subset=[_grad], cmap="Greens")
    if _grad_ok("Surv%"):
        sty = sty.background_gradient(subset=["Surv%"], cmap="RdYlGn")
    if _grad_ok("vsADP"):
        sty = sty.background_gradient(subset=["vsADP"], cmap="PuOr")
    sty = (sty
           .format({k: v for k, v in _fmt.items() if k in df.columns}, na_rep="—"))
    # Pin the name so it stays put while the numbers scroll. Without this a phone
    # user scrolls right to read Surv% and can no longer see WHOSE it is.
    _colcfg = {"Player": st.column_config.TextColumn("Player", pinned=True, width=150)}
    for _c, _w in (("JJ", 48), ("Boone", 56), ("Clay", 50), ("Walt", 50),
                   ("Pos", 58), ("Tm", 48), ("Bye", 44), ("Score", 62), ("VOR", 56),
                   ("Tier", 58), ("Surv%", 62), ("ADP", 56), ("vsADP", 62),
                   ("CoW", 54), ("Arc", 54), ("Decl%", 60), ("BB", 56), ("Edge", 58)):
        if _c in df.columns:
            _colcfg[_c] = st.column_config.Column(_c, width=_w)
    # the whole board is a pick control, not just the five chips above. Keying the
    # widget on the pick count gives each pick a FRESH selection -- otherwise the
    # row stays selected through the rerun and re-fires do_pick every time.
    _sel = st.dataframe(sty, width="stretch", hide_index=True, height=620,
                        column_config=_colcfg,
                        selection_mode="single-row", on_select="rerun",
                        key=f"ba_{len(ss.drafted)}_{_which}_{int(_compact)}"
                            f"_{'-'.join(sorted(_posf or []))}_{int(_experts)}")
    _rows = list(getattr(getattr(_sel, "selection", None), "rows", None) or [])
    if _rows and not done:
        do_pick(_pool[_rows[0]]["id"])
        st.rerun()
    st.caption("👆 Tap any row to draft that player." if on_clock_me
               else ("" if done else
                     f"👆 Tap any row to mark them drafted by {seat_name(res['on_clock'])}."))
    with st.expander("What the columns mean"):
        st.markdown(
            "- **VOR** — points above the last startable player at his position *in this league*.\n"
            "- **Surv%** — chance he lasts to your next pick (Monte-Carlo on ADP + the live run read).\n"
            "- **vsADP** — picks past his own ADP he has already fallen. `+20` = a bargain here; "
            "`−20` = taking him now is a reach.\n"
            "- **JJ / Boone / Clay / Walt** — each expert's POSITIONAL rank "
            "(JJ Zachariason, Justin Boone, Mike Clay, WalterFootball), shown with "
            "the Experts toggle. All four already feed our consensus rank, so a "
            "player they all have well above his `Pos` here is one our model is "
            "alone on.\n"
            "- **CoW** — cost of waiting: value you lose at that position by passing this round.\n"
            "- **Arc** — where our projection sits in the distribution of what comparable players "
            "did NEXT (same position, career year, pedigree). `!` = we project above almost all of "
            "them; `+` = below most. **Decl%** = share of those comps who fell off >25%. "
            "Read them together — near the top of the board nearly everyone reads high on Arc, so "
            "Decl% is what separates an aggressive projection from a risky one.")

# --------------------------------------------------------------------------- rails
r1, r2, r3 = st.columns([2, 2, 2], gap="medium")

with r1:
    st.markdown('<div class="dw-h">📊 Position run — last 24 picks</div>', unsafe_allow_html=True)
    st.markdown(run_strip_html(cfg, ss.drafted, by_id, sstate), unsafe_allow_html=True)

    st.markdown('<div class="dw-h">🎯 Strategy read</div>', unsafe_allow_html=True)
    note = res["strategy"]["note"]
    if note:
        st.info(note)
    else:
        st.caption("No strong run yet — take best value.")
    dem = res["opponents"]["demand"]
    if dem:
        st.caption("Teams before your pick most need: "
                   + ", ".join(f"{k}×{v}" for k, v in sorted(dem.items(), key=lambda x: -x[1])))
    cow = {k: v for k, v in res["cost_of_waiting"].items() if v and v > 3}
    if cow:
        st.caption("Value lost by waiting a round: "
                   + ", ".join(f"{k} −{v:.0f}" for k, v in sorted(cow.items(), key=lambda x: -x[1])))

with r2:
    st.markdown('<div class="dw-h">👤 Your roster</div>', unsafe_allow_html=True)
    if res["my_roster"]:
        st.dataframe(pd.DataFrame([{"Pos": p["pos"], "Player": p["name"], "VOR": p["vor"]}
                                   for p in res["my_roster"]]),
                     width="stretch", hide_index=True, height=min(320, 40 + 35 * len(res["my_roster"])))
    else:
        st.caption("No picks yet.")
    need = res["needs"]
    st.caption("Roster need (higher = more urgent): " +
               "  ".join(f"{k} {v:+.0f}" for k, v in sorted(need.items(), key=lambda x: -x[1])
                         if k not in ("K", "DST") or v > -20))

    if len(ss.drafted) >= 2 * cfg.teams and not done:
        g = grade_draft(cfg, ss.drafted, working)
        st.markdown('<div class="dw-h">📈 Draft grade so far</div>', unsafe_allow_html=True)
        gc1, gc2 = st.columns([1, 2])
        gc1.metric("Grade", g["grade"])
        gc2.metric(f"Rank {g['my_rank']}/{g['teams']}",
                   f"{g['pctile']}th pctile · {g['my_value']} vs lg avg {g['league_avg']}")

with r3:
    st.markdown('<div class="dw-h">🪜 Tiers remaining</div>', unsafe_allow_html=True)
    tier_rows = []
    seen = set()
    for p in sorted(res["best_available"], key=lambda x: (x["pos"], x.get("tier") or 99)):
        keyt = (p["pos"], p.get("tier"))
        if p["pos"] in ("K", "DST") or keyt in seen or not p.get("tier"):
            continue
        seen.add(keyt)
        n = sum(1 for q in res["best_available"] if q["pos"] == p["pos"] and q.get("tier") == p.get("tier"))
        tier_rows.append({"Pos": p["pos"], "Tier": p["pos"] + "T" + str(p["tier"]),
                          "Left": n, "Top": p["name"]})
    if tier_rows:
        st.dataframe(pd.DataFrame(tier_rows).sort_values(["Pos", "Tier"]),
                     width="stretch", hide_index=True, height=260)

# --------------------------------------------------------------------------- tabs
st.divider()
t_board, t_teams, t_feed, t_plan, t_mark, t_hist = st.tabs(
    ["🗺️ Draft board", "👥 Team rosters", "📜 Pick feed", "📋 Draft plan",
     "🔍 Mark a pick", "📚 Mock history"])

with t_board:
    _full = st.toggle("Show all rounds", value=False,
                      help="Off = a window around the live pick, which is what fits on a phone.")
    st.markdown(draft_board_html(cfg, sstate, ss.drafted, by_id,
                                 rounds_window=None if _full else 7),
                unsafe_allow_html=True)
    st.caption("Colored = drafted (by position) · ★ = your seat · orange = on the clock · "
               "blue = your future picks"
               + (" · ⇄ = traded pick, now the tagged team's" if sstate else ""))

with t_teams:
    st.markdown('<div class="dw-h">Everyone&rsquo;s team</div>', unsafe_allow_html=True)
    _tend_t = TEND if (sstate and TEND
                       and str(TEND.get("league_id")) == str(sstate.get("league_id"))) else None
    st.markdown(team_rosters_html(cfg, sstate, ss.drafted, by_id, cfg.starters,
                                  tendencies=_tend_t),
                unsafe_allow_html=True)
    st.caption("Counts are against this league's STARTING requirement — "
               "`RB 3/2` means three rostered for two slots, `DST 0/1` is a hole. "
               "The pick each player went at is beside his name.")
    st.divider()
    st.markdown('<div class="dw-h">Roster shape — every seat</div>', unsafe_allow_html=True)
    st.markdown(roster_matrix_html(cfg, sstate, ss.drafted, by_id, cfg.starters),
                unsafe_allow_html=True)
    st.caption("“Still needs” counts unfilled STARTING slots (FLEX not included) — "
               "a seat that owes a QB in round 12 is taking a QB.")
    st.divider()
    _sl = st.selectbox("Inspect a team", list(range(1, cfg.teams + 1)),
                       index=min(cfg.my_slot, cfg.teams) - 1,
                       format_func=lambda s: seat_name(s) + (" ★ you" if s == cfg.my_slot else ""))
    _r = team_roster(_sl)
    if _r:
        st.dataframe(pd.DataFrame([{"Pk": o, "At": pick_label(cfg, o), "Pos": p["pos"],
                                    "Player": p["name"], "Tm": p.get("team"),
                                    "Bye": p.get("bye")} for o, p in _r]),
                     hide_index=True, width="stretch", height=300)
        _c = pd.Series([p["pos"] for _, p in _r]).value_counts()
        st.caption("  ".join(f"{k} {v}" for k, v in _c.items()))
    else:
        st.caption("No picks yet.")

with t_feed:
    if ss.drafted:
        n = len(ss.drafted)
        since = int(ss.get("last_my_pick") or 0)
        window = n - since if (since and n > since) else min(24, n)
        st.markdown(f'<div class="dw-h">'
                    + (f"Gone since your last pick ({window})" if since and n > since
                       else "Recently drafted")
                    + '</div>', unsafe_allow_html=True)
        rrows = []
        for overall in range(n, max(0, n - max(window, 24)), -1):
            p = by_id.get(ss.drafted[overall - 1])
            if not p:
                continue
            slot = team_on_clock(cfg, overall)
            # `by_id` holds RAW board dicts -- _vor only exists on analyze()'s
            # internal copy, so reading it here would render a silently blank
            # column. ADP is on the board itself and is the useful read anyway:
            # it shows who is going early vs the market.
            rrows.append({"Pk": overall, "At": pick_label(cfg, overall),
                          "By": ("★ YOU" if slot == cfg.my_slot else seat_name(slot)),
                          "Player": p["name"], "Pos": p["pos"], "ADP": p.get("adp"),
                          "vs ADP": (None if p.get("adp") is None
                                     else round(overall - p["adp"]))})
        st.dataframe(pd.DataFrame(rrows), hide_index=True, width="stretch", height=420)
        st.caption("**vs ADP** — positive means he lasted past his ADP (a value pick), "
                   "negative means that team reached.")
    else:
        st.caption("No picks yet.")

with t_plan:
    st.caption("Monte-Carlo your remaining picks (opponents pick by ADP, you by your Strategy) "
               "to see your likely build path and where each position's value dries up.")
    if bb_mode:
        # plan_draft picks its simulated future selves with effective_vor /
        # roster_factor / need -- the redraft value model. In best ball the
        # actual recommendation comes from bestball.py instead, so the plan
        # would confidently describe a build the wizard will not make. A plan
        # that contradicts the pick is worse than no plan, so it is disabled
        # rather than shown with a caveat. (Porting it means routing its
        # my-pick policy through _bb_values, the same one-helper rule that
        # ROSTER_INTERP needed.)
        st.info("Not available in Best Ball mode — the forward planner still "
                "uses the redraft value model, so it would contradict the "
                "recommendation. Tracked as a follow-up.")
    elif st.button("Run / refresh plan", key="planbtn", type="primary"):
        ss["plan"] = plan_draft(working, cfg, ss.drafted, n_sims=150)
    plan = ss.get("plan")
    if plan and plan.get("picks"):
        if plan.get("note"):
            st.write("**" + plan["note"] + "**")
        prows = [{
            "Pick": p["pick_no"], "At": pick_label(cfg, p["pick_no"]), "Rd": p["round"],
            "Target": p["top_pos"],
            "Conf": f"{int(max(p['pos_probs'].values())*100)}%" if p["pos_probs"] else "",
            "ExpVOR": p["exp_vor"],
            "Often there": ", ".join(surname(e) for e in p["examples"]),
        } for p in plan["picks"][:14]]
        st.dataframe(pd.DataFrame(prows), hide_index=True, width="stretch")

with t_mark:
    if not done:
        undrafted = [p for p in working if p["id"] not in set(ss.drafted)]
        label = {f"{p['name']} · {p['pos']}-{p.get('team','')}": p["id"] for p in undrafted}
        _prompt = ("Search a player to draft:" if (st.session_state.get("practice") or on_clock_me)
                   else "Search a player who was just drafted:")
        pick_label_sel = st.selectbox(_prompt, [""] + list(label.keys()))
        if st.button("Mark drafted", type="primary") and pick_label_sel:
            do_pick(label[pick_label_sel]); st.rerun()
        st.caption("Use this for anyone not in the top 60 — kickers, defenses, or a "
                   "name our board ranks lower than the room does.")
    else:
        st.caption("Draft complete.")

_mode_lbl = "Rookie" if rookie_mode else ("Best Ball" if bb_mode else "Redraft")
_basis = ("dynasty value (our model + age curve)" if rookie_mode else
          ("marginal value added to your OPTIMAL WEEKLY LINEUP (ceiling, depth "
           "and bye coverage priced in) · ⚠ not yet validated to beat the "
           "redraft engine — see BB_REPL_WEIGHT in draft_engine.py" if bb_mode
           else "consensus = our model + Waldman blend, Clay ECR, FFC ADP"))
st.caption(f"{_mode_lbl} board: {len(working)} players · "
           f"{res['board_size_remaining']} undrafted · " + _basis)


with t_hist:
    ss.setdefault("mock_history", MH.merge(MH.load_disk(), []))
    hist = ss["mock_history"]
    if not hist:
        st.caption("No finished mocks yet. Complete a practice draft and it lands here.")
    else:
        smry = MH.summarise(hist)
        hc = st.columns(3)
        hc[0].metric("Mocks logged", smry["n"])
        hc[1].metric("Average finish", f"{smry['avg_finish']} of {hist[-1]['teams']}"
                     if smry.get("avg_finish") else "—")
        hc[2].metric("Avg left on the board", f"{smry['avg_left']} VOR",
                     help="Mean total value your reviewed misses cost you per mock. "
                          "This is the number to drive down.")
        if smry.get("pos_edge"):
            st.caption("Your average edge by position across all logged mocks: "
                       + "  ·  ".join(f"**{k}** {v:+d}" for k, v in
                                      sorted(smry["pos_edge"].items(), key=lambda x: -x[1]))
                       + " — a consistently negative position is a habit, not variance.")
        st.dataframe(pd.DataFrame([{
            "When": r["when"], "Room": r["room"], "League": f"{r['teams']}T {r['scoring'].upper()}"
                                                            + (" SF" if r.get("superflex") else ""),
            "Slot": r["slot"], "Grade": r["grade"], "Finish": r["rank"],
            "Value": r["value"], "vs avg": r["edge"], "Roster": r["shape"],
            "Misses": r["n_misses"], "Left": r["left_on_board"],
            "Biggest miss": r.get("top_miss"),
        } for r in reversed(hist)]), hide_index=True, width="stretch", height=340)

    st.divider()
    # ⚠ Streamlit Cloud's filesystem is EPHEMERAL -- a write succeeds and then
    # disappears on the next restart, and is not shared across devices. Saying
    # "saved" on the strength of the write landing would be a lie on the phone, so
    # report what actually happened and make Download the durable path.
    if ss.get("hist_saved"):
        st.caption("Saved to `data/mock_history.json` on this machine. ⚠ On the "
                   "hosted app that file does **not** survive a restart — use "
                   "Download to keep a copy.")
    else:
        st.caption("⚠ Kept for this session only — the hosted app has no durable "
                   "storage. Download to keep it.")
    dc = st.columns(2)
    dc[0].download_button("⬇ Download history (JSON)",
                          data=json.dumps({"mocks": hist}, indent=1),
                          file_name="mock_history.json", mime="application/json",
                          width="stretch", disabled=not hist)
    up = dc[1].file_uploader("⬆ Restore a downloaded history", type="json",
                             label_visibility="collapsed")
    if up is not None:
        try:
            rows = json.loads(up.read().decode("utf-8")).get("mocks", [])
            before = len(ss["mock_history"])
            ss["mock_history"] = MH.merge(ss["mock_history"], rows)
            MH.save_disk(ss["mock_history"])
            st.success(f"Restored — {len(ss['mock_history']) - before} new of "
                       f"{len(rows)} (duplicates skipped).")
        except Exception as e:
            st.error(f"Could not read that file: {e}")
