"""
draft_app.py  --  Draft Wizard (Streamlit)
===========================================
Phone-friendly live draft assistant. Mark players off as they're drafted (tap a
chip, search, or auto-sync from Sleeper) and it recomputes the best pick, tiers,
survival odds, and how your opponents are drafting after every pick.

Local:   streamlit run draft_wizard/draft_app.py
Phone:   deploy this folder to Streamlit Community Cloud (see README) -> open the
         https URL on your phone.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent))
from draft_engine import (load_board, LeagueConfig, analyze, plan_draft,   # noqa: E402
                          ARCHETYPES, ARCHETYPE_LABEL, prep_valued, mock_advance,
                          team_on_clock, grade_draft)
from draft_names import norm_name, pos_norm                          # noqa: E402
from draft_news import (fetch_news, player_status, apply_status,     # noqa: E402
                        items_for_player, player_ids_in_news, ago)

# quick-league presets (the main axes; roster stays standard, your slot is separate)
PRESETS = {
    "12-team PPR (1QB)":       dict(teams=12, scoring="ppr",      superflex=False),
    "12-team Half PPR (1QB)":  dict(teams=12, scoring="half",     superflex=False),
    "12-team PPR Superflex":   dict(teams=12, scoring="ppr",      superflex=True),
    "10-team PPR (1QB)":       dict(teams=10, scoring="ppr",      superflex=False),
    "14-team PPR (1QB)":       dict(teams=14, scoring="ppr",      superflex=False),
    "12-team Standard (1QB)":  dict(teams=12, scoring="standard", superflex=False),
}


def _load_league_presets():
    """Merge the generic presets with YOUR real leagues from data/league_presets.json
    (generated by import_leagues.py from Sleeper/ESPN)."""
    merged = {k: dict(v) for k, v in PRESETS.items()}
    p = Path(__file__).parent / "data" / "league_presets.json"
    if p.exists():
        try:
            for x in json.load(open(p, encoding="utf-8")).get("presets", []):
                merged[x["name"]] = x
        except Exception:
            pass
    return merged


ALL_PRESETS = _load_league_presets()

st.set_page_config(page_title="Draft Wizard", page_icon="🏈", layout="wide",
                   initial_sidebar_state="expanded")


@st.cache_data(show_spinner=False)
def get_board():
    return load_board()


@st.cache_data(ttl=600, show_spinner="📰 Loading NFL beat feed (team writers)…")
def get_news():
    """All-team beat-writer feed (Google News per team) + national outlets,
    tagged to the board. Cached 10 min; the sidebar's Refresh clears it."""
    from draft_news import SOURCES, team_sources
    return fetch_news(get_board(), sources=SOURCES + team_sources())


def get_source_health():
    from draft_news import SOURCES, team_sources, check_sources
    return check_sources(SOURCES + team_sources())


def build_rookie_board(board):
    """Rookie-draft view: rookies only, valued by the REAL dynasty market
    (DynastyProcess superflex value) when available, else our dynasty value.
    Pseudo rookie-ADP = that value's rank (no public rookie-draft ADP feed)."""
    rb = []
    for p in board:
        if not p.get("rookie"):
            continue
        q = dict(p)
        q["pts"] = p.get("dp2") or p.get("dp1") or p.get("dyn") or p.get("pts") or 0.0
        q["rec"] = 0.0
        rb.append(q)
    rb.sort(key=lambda x: -x["pts"])
    for i, q in enumerate(rb, 1):
        q["adp"], q["adp_sd"], q["adp_sf"] = float(i), 3.0 + 0.12 * i, None
    return rb


board = get_board()
ss = st.session_state
ss.setdefault("drafted", [])          # ordered list of drafted player ids

mode = st.sidebar.radio("Draft type", ["Redraft", "Rookie (dynasty)"], horizontal=True)
rookie_mode = mode.startswith("Rookie")
st.sidebar.checkbox("🎮 Practice (mock draft vs AI)", key="practice",
                    help="AI drafts the other teams by ADP; you make your own picks.")
working = build_rookie_board(board) if rookie_mode else board
by_id = {p["id"]: p for p in working}
key_map = {(norm_name(p["name"]), p["pos"]): p["id"] for p in working}   # for Sleeper/manual matching


# --------------------------------------------------------------------------- helpers
def draft_ids(ids):
    for pid in ids:
        if pid and pid not in ss.drafted:
            ss.drafted.append(pid)


def undo():
    if ss.drafted:
        ss.drafted.pop()


def sleeper_sync(draft_id: str):
    import requests
    url = f"https://api.sleeper.app/v1/draft/{draft_id.strip()}/picks"
    r = requests.get(url, timeout=15)
    r.raise_for_status()
    picks = sorted(r.json(), key=lambda x: x.get("pick_no", 0))
    matched, missed = [], []
    for pk in picks:
        m = pk.get("metadata") or {}
        nm = f"{m.get('first_name','')} {m.get('last_name','')}".strip()
        pos = pos_norm(m.get("position"))
        pid = key_map.get((norm_name(nm), pos))
        (matched.append(pid) if pid else missed.append(f"{nm} ({pos})"))
    ss.drafted = [p for p in matched if p]
    return len(matched), missed


def do_pick(pid):
    """Commit a pick; in practice mode, let the AI draft the other teams up to your next pick."""
    draft_ids([pid])
    if st.session_state.get("practice"):
        ss.drafted = mock_advance(prep_valued(working, cfg), cfg, ss.drafted, np.random.default_rng())


# --------------------------------------------------------------------------- sidebar: league
with st.sidebar:
    st.header("🏈 League setup")
    preset = st.selectbox("Quick league", ["Custom"] + list(ALL_PRESETS),
                          help="Your real leagues (from Sleeper/ESPN) + generic setups, or Custom.")
    teams = st.number_input("Teams", 4, 16, 12)
    if not rookie_mode:
        scoring = st.selectbox("Scoring", ["ppr", "half", "standard"],
                               format_func=lambda s: {"ppr": "PPR", "half": "Half-PPR", "standard": "Standard"}[s])
        superflex = st.checkbox("Superflex (2 QB slots)")
        archetype = st.selectbox("Strategy", ARCHETYPES, format_func=lambda a: ARCHETYPE_LABEL[a],
                                 help="Best value = fully reactive (VOR + run-aware). Others commit to a structural plan.")
    else:
        scoring, superflex, archetype = "ppr", False, "value"
        r_rounds = st.number_input("Rookie draft rounds", 1, 8, 5)
        r_linear = st.checkbox("Linear draft (not snake)")
        st.caption("Rookies valued by dynasty value; pseudo-ADP = dynasty rank (no public rookie ADP yet).")
    my_slot = st.number_input("Your draft slot", 1, int(teams), 1)
    with st.expander("Starting lineup / bench"):
        c1, c2 = st.columns(2)
        n_qb = c1.number_input("QB", 0, 3, 1)
        n_rb = c2.number_input("RB", 0, 4, 2)
        n_wr = c1.number_input("WR", 0, 4, 2)
        n_te = c2.number_input("TE", 0, 3, 1)
        n_fx = c1.number_input("FLEX", 0, 3, 1)
        n_sf = c2.number_input("SUPERFLEX", 0, 2, 1 if superflex else 0)
        n_k = c1.number_input("K", 0, 2, 1)
        n_dst = c2.number_input("DST", 0, 2, 1)
        bench = st.number_input("Bench", 0, 15, 6)
    starters = {"QB": n_qb, "RB": n_rb, "WR": n_wr, "TE": n_te,
                "FLEX": n_fx, "SUPERFLEX": n_sf, "K": n_k, "DST": n_dst}
    if rookie_mode:
        cfg = LeagueConfig(teams=int(teams), scoring="ppr", starters=starters, bench=int(bench),
                           my_slot=int(my_slot), snake=not r_linear, rounds=int(r_rounds),
                           archetype="value")
    else:
        cfg = LeagueConfig(teams=int(teams), scoring=scoring, superflex=superflex,
                           starters=starters, bench=int(bench), my_slot=int(my_slot),
                           archetype=archetype)
    if preset != "Custom":                                # a quick-league preset defines the league
        P = ALL_PRESETS[preset]
        st_p = P.get("starters", starters)
        slot_p = min(int(my_slot), int(P["teams"]))
        if rookie_mode:
            cfg = LeagueConfig(teams=int(P["teams"]), scoring="ppr", superflex=P.get("superflex", False),
                               starters=st_p, bench=int(P.get("bench", bench)), my_slot=slot_p,
                               snake=not r_linear, rounds=int(P.get("rounds", r_rounds)), archetype="value")
        else:
            cfg = LeagueConfig(teams=int(P["teams"]), scoring=P.get("scoring", "ppr"),
                               superflex=P.get("superflex", False), starters=st_p,
                               bench=int(P.get("bench", bench)), my_slot=slot_p, archetype=archetype)
        if P.get("kind") == "rookie" and not rookie_mode:
            st.info("Dynasty rookie league — set **Draft type → Rookie** at the top.")
        elif P.get("kind") == "redraft" and rookie_mode:
            st.info("Redraft league — set **Draft type → Redraft** at the top.")

    st.divider()
    st.subheader("🔄 Sleeper live-sync")
    did = st.text_input("Draft ID", help="From your Sleeper draft URL: sleeper.com/draft/nfl/<DRAFT_ID>")
    if st.button("Pull picks from Sleeper", width="stretch") and did:
        try:
            n, missed = sleeper_sync(did)
            st.success(f"Synced {n} picks.")
            if missed:
                st.caption("Unmatched: " + ", ".join(missed[:8]))
        except Exception as e:
            st.error(f"Sync failed: {e}")

    st.divider()
    st.subheader("📰 NFL beat feed")
    ss.setdefault("feed_on", True)
    ss.setdefault("feed_influence", True)
    st.checkbox("Show beat feed", key="feed_on",
                help="Team beat-writer reporting (free Google News per team) + ESPN/CBS/Yahoo/PFT, "
                     "tagged to your board.")
    st.checkbox("Apply signals to picks", key="feed_influence",
                help="Injuries, IR, benchings and role changes adjust VOR and the recommendation. "
                     "Turn off for display-only.")
    if st.button("🔄 Refresh feed", width="stretch"):
        get_news.clear(); st.rerun()
    st.caption("Signals: ⛔OUT/🔴IR/🟡questionable/↩︎returning · ⬆︎starter/⬇︎benched/↕︎backup.")

    st.divider()
    if st.button("↩︎ Undo last pick", width="stretch"):
        undo(); st.rerun()
    if st.button("🗑 Reset draft", width="stretch"):
        ss.drafted = []; ss.pop("plan", None); ss["started"] = False; st.rerun()


# --------------------------------------------------------------------------- start gate
ss.setdefault("started", False)
if not ss["started"]:
    st.title("🏈 Draft Wizard")
    _sf = " Superflex" if cfg.superflex else ""
    _summ = f"**{mode}** · {cfg.teams}-team {cfg.scoring.upper()}{_sf} · your slot **{cfg.my_slot}**"
    if rookie_mode:
        _summ += f" · {cfg.total_rounds()} rounds"
    if ss.get("practice"):
        _summ += " · 🎮 practice (AI drafts the other teams)"
    st.info(_summ)
    if st.button("▶ Start draft", type="primary", width="stretch"):
        ss.drafted = []
        ss.pop("plan", None)
        if ss.get("practice"):
            ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], np.random.default_rng())
        ss["started"] = True
        st.rerun()
    st.caption("Set your league, strategy, slot, and Redraft/Rookie + Practice in the sidebar "
               "(☰ top-left), then hit Start.")
    st.stop()

# --------------------------------------------------------------------------- beat feed + signals
news = {"items": [], "errors": [], "fetched_at": 0}
status = {}
feed_changes = []
if ss.get("feed_on"):
    try:
        news = get_news()
    except Exception as e:
        st.warning(f"📰 Beat feed unavailable right now: {e}")
    status = player_status(news)
    if ss.get("feed_influence") and status:
        working, feed_changes = apply_status(working, status)   # scale VOR by injury/role
        by_id = {p["id"]: p for p in working}
news_player_ids = player_ids_in_news(news)

# --------------------------------------------------------------------------- analyze
res = analyze(working, cfg, ss.drafted)
on_clock_me = res["on_clock"] == cfg.my_slot

# --------------------------------------------------------------------------- header
h1, h2, h3 = st.columns([2, 2, 3])
h1.metric("Pick", f"{res['current_overall']}  (Rd {res['round']})")
h2.metric("On the clock", f"Team {res['on_clock']}" + ("  ← YOU" if on_clock_me else ""))
h3.metric("Your next pick", f"{res['my_next_pick']}  ({res['picks_until_mine']} away)"
          if res["my_next_pick"] else "—")
if on_clock_me:
    st.success("🟢 **You're on the clock**")
if feed_changes:
    _summ = ", ".join(f"{c['name'].split()[-1]} {c['label']} ×{c['factor']}" for c in feed_changes[:6])
    st.caption(f"📰 Beat-feed adjustments applied to {len(feed_changes)} player(s): {_summ}"
               + (" …" if len(feed_changes) > 6 else ""))

# --------------------------------------------------------------------------- draft controls (always visible)
uc = st.columns([1, 1, 4])
if uc[0].button("↩︎ Undo", width="stretch"):
    undo(); st.rerun()
if uc[1].button("🗑 Reset draft", width="stretch"):
    ss.drafted = []; ss.pop("plan", None); ss["started"] = False; st.rerun()

# --------------------------------------------------------------------------- practice controls
if st.session_state.get("practice"):
    pc = st.container(border=True)
    pc.write(f"🎮 **Practice mode** — AI drafts the other {cfg.teams - 1} teams by ADP; you pick your own.")
    pcc = pc.columns(3)
    if pcc[0].button("▶ Sim to my pick", width="stretch"):
        ss.drafted = mock_advance(prep_valued(working, cfg), cfg, ss.drafted, np.random.default_rng())
        st.rerun()
    if pcc[1].button("🔄 New mock", width="stretch"):
        ss.drafted = mock_advance(prep_valued(working, cfg), cfg, [], np.random.default_rng())
        st.rerun()
    if pcc[2].button("⏭ Auto-draft rest", width="stretch",
                     help="AI finishes the whole draft, picking your team by your Strategy"):
        valued = prep_valued(working, cfg); rng = np.random.default_rng()
        total = cfg.teams * cfg.total_rounds(); guard = 0
        while len(ss.drafted) < total and guard < total + 5:
            ss.drafted = mock_advance(valued, cfg, ss.drafted, rng)
            if len(ss.drafted) >= total:
                break
            _r = analyze(working, cfg, ss.drafted).get("recommendation")
            if not _r:
                break
            ss.drafted.append(_r["id"]); guard += 1
        st.rerun()

# --------------------------------------------------------------------------- recommendation
rec = res["recommendation"]
if rec:
    surv = rec["survival"] * 100
    box = st.container(border=True)
    box.markdown(
        f"### ⭐ {rec['name']}  —  {rec['pos']}{rec['posrank']} · {rec['team']}\n"
        f"**VOR {rec['vor']}**  ·  Tier {rec['pos']}T{rec['tier']} ({rec['tier_left']} left in tier)  ·  "
        f"survives to your pick **{surv:.0f}%**\n\n"
        f"➡︎ _{rec['reason']}_")
    _rs = status.get(rec["id"])
    if _rs and _rs.get("label"):
        _src = _rs.get("byline") or _rs.get("source") or ""
        box.warning(f"📰 **{_rs['label']}** — {_rs['title']} "
                    f"({_src} · {ago(_rs.get('published'))})", icon="⚠️")
    if on_clock_me:
        b1, b2 = box.columns([1, 3])
        if b1.button(f"✅ Draft {rec['name'].split()[-1]}", width="stretch", type="primary"):
            do_pick(rec["id"]); st.rerun()
    else:
        box.caption(f"🎯 Your target for pick {res['my_next_pick']}. "
                    f"⏳ Team {res['on_clock']} is on the clock — tap who they take below.")

    # marking / quick-pick row (context-aware)
    if st.session_state.get("practice"):
        _cap = "Quick-pick a player for your team:"
    elif on_clock_me:
        _cap = "Your pick — tap your player, or use Draft above:"
    else:
        _cap = f"Tap who Team {res['on_clock']} just drafted:"
    st.caption(_cap)
    chips = st.columns(5)
    for i, a in enumerate(res["best_available"][:5]):
        if chips[i].button(f"{a['name'].split()[-1]} {a['pos']}", key=f"chip_{i}", width="stretch"):
            do_pick(a["id"]); st.rerun()

# manual mark-off (search anyone)
undrafted = [p for p in working if p["id"] not in set(ss.drafted)]
label = {f"{p['name']} · {p['pos']}-{p.get('team','')}": p["id"] for p in undrafted}
pick_label = st.selectbox("Or search a player who was just drafted:", [""] + list(label.keys()))
if st.button("Mark drafted") and pick_label:
    do_pick(label[pick_label]); st.rerun()

with st.expander("📋 Draft plan — simulate the rest of your draft"):
    st.caption("Monte-Carlo your remaining picks (opponents pick by ADP, you by your Strategy) "
               "to see your likely build path and where each position's value dries up.")
    if st.button("Run / refresh plan", key="planbtn"):
        ss["plan"] = plan_draft(working, cfg, ss.drafted, n_sims=150)
    plan = ss.get("plan")
    if plan and plan.get("picks"):
        if plan.get("note"):
            st.write("**" + plan["note"] + "**")
        prows = [{
            "Pick": p["pick_no"], "Rd": p["round"], "Target": p["top_pos"],
            "Conf": f"{int(max(p['pos_probs'].values())*100)}%" if p["pos_probs"] else "",
            "ExpVOR": p["exp_vor"],
            "Often there": ", ".join(e.split()[-1] for e in p["examples"]),
        } for p in plan["picks"][:12]]
        st.dataframe(pd.DataFrame(prows), hide_index=True, width="stretch")

# --------------------------------------------------------------------------- beat feed panel
if ss.get("feed_on"):
    _errs = news.get("errors", [])
    _n = len(news.get("items", []))
    with st.expander(f"📰 NFL beat feed — {_n} items"
                     + (f" · {len(_errs)} sources down" if _errs else ""), expanded=False):
        drafted_set = set(ss.drafted)
        my_ids = {p["id"] for p in res["my_roster"]}
        undrafted_ids = {p["id"] for p in working if p["id"] not in drafted_set}
        view = st.radio("Show", ["Draftable", "Signals only", "My roster", "Everything"],
                        horizontal=True, key="feed_view",
                        help="Draftable = news about players still on the board.")

        def _keep(it):
            pids = it.get("player_ids", [])
            if view == "Everything":
                return True
            if view == "My roster":
                return any(pid in my_ids for pid in pids)
            if view == "Signals only":
                return any(pid in status for pid in pids)
            return any(pid in undrafted_ids for pid in pids)   # Draftable

        shown = 0
        for it in news.get("items", []):
            if not _keep(it):
                continue
            shown += 1
            if shown > 40:
                break
            tags = []
            for pid in it.get("player_ids", [])[:4]:
                p = by_id.get(pid) or {}
                nm = p.get("name", "")
                sl = status.get(pid, {}).get("label", "")
                tags.append(f"**{nm}**" + (f" _{sl}_" if sl else ""))
            src = it.get("byline") or it.get("source") or ""
            team = f" · {it['team']}" if it.get("team") else ""
            when = ago(it.get("published"))
            head = f"[{it['title']}]({it['url']})" if it.get("url") else it["title"]
            st.markdown(f"**{when}** — {head}")
            meta = f"<small>{src}{team}" + (" · " + " · ".join(tags) if tags else "") + "</small>"
            st.markdown(meta, unsafe_allow_html=True)
        if shown == 0:
            st.caption("No matching items. Try 'Everything', or Refresh feed in the sidebar.")

        st.divider()
        st.caption("🩺 **Source health** — run this on your live deployment to see which feeds are up.")
        if st.button("Check sources"):
            with st.spinner("Pinging feeds…"):
                ss["src_health"] = get_source_health()
        health = ss.get("src_health")
        if health:
            up = sum(1 for r in health if r["ok"])
            st.caption(f"{up}/{len(health)} sources up · "
                       f"{sum(r['count'] for r in health)} items · "
                       f"median {int(np.median([r['ms'] for r in health]))}ms")
            hrows = [{"Source": r["name"], "Team": r.get("team") or "—",
                      "OK": "✅" if r["ok"] else "❌", "Items": r["count"],
                      "ms": r["ms"], "Error": (r["error"] or "")[:60]} for r in health]
            st.dataframe(pd.DataFrame(hrows), hide_index=True, width="stretch", height=300)
    if _errs:
        st.caption("Sources currently down: " + ", ".join(e[0] for e in _errs[:8])
                   + (" …" if len(_errs) > 8 else ""))

st.divider()

# --------------------------------------------------------------------------- main columns
left, right = st.columns([3, 2])

with left:
    st.subheader("Best available")
    rows = []
    for p in res["best_available"][:40]:
        _st = status.get(p["id"])
        _news = _st["label"] if _st and _st.get("label") else ("📰" if p["id"] in news_player_ids else "")
        rows.append({
            "Player": p["name"], "Pos": f"{p['pos']}{p['posrank']}", "Tm": p.get("team"),
            "News": _news,
            "VOR": p["vor"], "Tier": f"{p['pos']}T{p['tier']}" if p.get("tier") else "",
            "Surv%": round((p.get("survival") or 1) * 100),
            "ADP": p.get("adp"), "CoW": p.get("cost_of_waiting"),
        })
    df = pd.DataFrame(rows)
    sty = (df.style
           .background_gradient(subset=["VOR"], cmap="Greens")
           .background_gradient(subset=["Surv%"], cmap="RdYlGn")
           .format({"VOR": "{:.0f}", "ADP": "{:.0f}", "CoW": "{:.0f}", "Surv%": "{:.0f}"}, na_rep="—"))
    st.dataframe(sty, width="stretch", hide_index=True, height=560)

with right:
    if ss.drafted:
        st.subheader("Recently drafted")
        n = len(ss.drafted)
        rrows = []
        for overall in range(n, max(0, n - 8), -1):
            p = by_id.get(ss.drafted[overall - 1])
            if not p:
                continue
            slot = team_on_clock(cfg, overall)
            rrows.append({"Pk": overall, "By": ("YOU" if slot == cfg.my_slot else f"T{slot}"),
                          "Player": p["name"], "Pos": p["pos"]})
        st.dataframe(pd.DataFrame(rrows), hide_index=True, width="stretch", height=180)

    if len(ss.drafted) >= 2 * cfg.teams:
        g = grade_draft(cfg, ss.drafted, working)
        st.subheader("Final draft grade" if res["my_next_pick"] is None else "Draft grade so far")
        gc1, gc2 = st.columns([1, 2])
        gc1.metric("Grade", g["grade"])
        gc2.metric(f"Rank {g['my_rank']}/{g['teams']}",
                   f"{g['pctile']}th pctile · {g['my_value']} vs lg avg {g['league_avg']}")

    st.subheader("Your roster")
    if res["my_roster"]:
        st.dataframe(pd.DataFrame([{"Pos": p["pos"], "Player": p["name"], "VOR": p["vor"]}
                                   for p in res["my_roster"]],
                                  ), width="stretch", hide_index=True)
    else:
        st.caption("No picks yet.")
    need = res["needs"]
    st.caption("Roster need (higher = more urgent): " +
               "  ".join(f"{k} {v:+.0f}" for k, v in sorted(need.items(), key=lambda x: -x[1])
                        if k not in ("K", "DST") or v > -20))

    st.subheader("Strategy read")
    note = res["strategy"]["note"]
    if note:
        st.info(note)
    else:
        st.caption("No strong run yet — take best value.")
    dem = res["opponents"]["demand"]
    if dem:
        st.caption("Teams before your pick most need: "
                   + ", ".join(f"{k}×{v}" for k, v in sorted(dem.items(), key=lambda x: -x[1])))
    cow = {k: v for k, v in res["cost_of_waiting"].items() if v and v > 3}
    if cow:
        st.caption("Value lost by waiting a round: "
                   + ", ".join(f"{k} −{v:.0f}" for k, v in sorted(cow.items(), key=lambda x: -x[1])))

    st.subheader("Tiers remaining")
    tier_rows = []
    seen = set()
    for p in sorted(res["best_available"], key=lambda x: (x["pos"], x.get("tier") or 99)):
        keyt = (p["pos"], p.get("tier"))
        if p["pos"] in ("K", "DST") or keyt in seen or not p.get("tier"):
            continue
        seen.add(keyt)
        n = sum(1 for q in res["best_available"] if q["pos"] == p["pos"] and q.get("tier") == p.get("tier"))
        tier_rows.append({"Pos": p["pos"], "Tier": p["pos"] + "T" + str(p["tier"]),
                          "Left": n, "Top": p["name"]})
    if tier_rows:
        st.dataframe(pd.DataFrame(tier_rows).sort_values(["Pos", "Tier"]),
                     width="stretch", hide_index=True, height=260)

st.caption(f"{'Rookie' if rookie_mode else 'Redraft'} board: {len(working)} players · "
           f"{res['board_size_remaining']} undrafted · "
           + ("dynasty value (our model + age curve)" if rookie_mode
              else "consensus = our model + Waldman blend, Clay ECR, FFC ADP"))
